// This needs to be flexhed out a lot, I've been adding them as needed
export const ABBREV: Record<string, string> = {
  "\\x": "×",
  "\\r": "→",
  "\\all": "∀",
  "\\\\": "\\",
  "\\==": "≡",
  "\\circ": "∘",
  "\\oplus": "⊕",
  "\\otimes": "⊗",
  "\\1": "₁",
  "\\2": "₂",
  "\\<": "⟨",
  "\\>": "⟩",
  "\\_0": "₀",
  "\\_1": "₁",
  "\\_2": "₂",
  "\\_3": "₃",
  "\\neg": "¬",
  "\\bN": "ℕ",
  "\\bZ": "ℤ",
  "\\gi": "ι",
  "\\gs": "σ",
  "\\gt": "τ",
  "\\gD": "Δ",
  "\\gG": "Γ"
};
