#!/bin/sh -e
REV=$(git rev-parse --short HEAD)
if ! git diff-index --quiet HEAD --; then
  REV="${REV}-dirty"
fi
cat >> src/Revision.newt.new <<EOF
module Revision

import Prelude

gitRevision : String
gitRevision = "$REV"
EOF
cmp src/Revision.newt.new src/Revision.newt || cp src/Revision.newt.new src/Revision.newt
rm -f src/Revision.newt.new
