#!/bin/sh
SAMPLES=$(find playground/samples -name "*.newt")
for i in tests/black/*.newt $SAMPLES aoc2024/*.newt; do
  ./build/exec/newt $i
  if [ $? != "0" ]; then
    echo FAIL $i
    exit -1
  fi
  echo $?
done

