[keys.insert.tab]
r = "@→"
x = "@×"
a = { "l" = { "l" = "@∀"}}
c = { "i" = { "r" = { "c" = "@∘"} } }
"=" = { "=" = "@≡"}
"n" = { "e" = { "g" = "@¬"}}
#
"[" = { "[" = "@⟦"}
"]" = { "]" = "@⟧"}
"0" = "@₀"
"1" = "@₁"
"2" = "@₂"
"3" = "@₃"
"b" = {"N" = "@ℕ", "Z" = "@ℤ"}
G = { "P" = "@∏", "S" = "@Σ", "D" = "@Δ", "G" = "@Γ", "l" = "@λ", "s" = "@σ", "t" = "@τ"}
