name: Publish Playground
concurrency:
    group: production
    cancel-in-progress: true
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: dependencies
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: setup
        run: |
          apt update
          apt-get install -y zip
          pack install contrib
      - name: use bun
        uses: oven-sh/setup-bun@v2
      - name: build
        run: |
          make
          cd playground
          npm install -g esbuild vite
          npm install
          mkdir public
          ./build
          vite build --base /newt
          #npm run build
      - name: Upload playground
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: playground/dist/
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4





